/*
* ErrorType.cs
*
* Description:
*
* This file is automatically generated from GuiErrorDescriptionTable.h
* defined for class CStatusControl.  Each time CStatusControl needed to
* re-compiled, this file will be re-generated again to make sure it is
* compatible with the newest version. It provides a enum type for all
* possible error cases a user could make when interact with the GUI.
*
* Important! Never attempt to change this file manually!
*/
namespace AlohaWebService {
	public enum GuiErrorType {
		SYSTEM_INTERNAL_ERROR,				// System internal error occurs, please restart Aloha and try again
		REQUEST_DENIED,						// Request is denied, since Aloha is busy serving some other client
		SOURCE_SLOT_EMPTY,					// Source slot is empty
		DESTINATION_SLOT_OCCUPIED,			// Destination slot is occupied
		SOURCE_SLOT_NOT_ASSIGNED,			// Source slot is not assigned
		ONE_SOURCE_SLOT_EMPTY,				// At least one source slot is empty in a dual arm transfer
		ONE_DESTINATION_SLOT_OCCUPIED,		// At least one destination slot is occupied in a dual arm transfer
		ALIGNER_ASSIGNED_AS_DESTINATION,	// Aligner cannot be assigned as a destination
		INVALID_FOUP_SLOT,					// Invalid Foup slot, a Foup contains 25 slots, make sure your choose be in place
		INVALID_LOADLOCK_SLOT,				// Invalid Loadlock slot, a Loadlock contains 4 slots, make sure your choose be in place
		INVALID_ROBOT_ARM,					// Invalid Robot arm, a Robot has 2 arms, make sure your choose be in place
		INVALID_ALIGNER_SLOT,				// Invalid Aligner slot, an Aligner has 1 slot, make sure your choose be in place
		SECOND_SLOT_INVALID,				// The second slot is invalid for a dual arm transfer
		INVALID_ALIGNER_SLOT_ASSIGNMENT,	// Invalid Aligner slot assignment for a dual arm transfer, since Aligner only has one slot
	}
}